Add functional conformance suite page
wso2/docs-ob-toolkit-uk pull request #75
Opened 2023-03-17 07:16 UTC by DinithiDiaz

## Purpose
This PR is to add the UK functional conformance suite page.
This will fix https://github.com/wso2/docs-open-banking/issues/686.

2023-03-17 08:28 UTC, DinithiDiaz commented
Please find a locally built copy of the page for reference:

[functional-conformance-suite.pdf](https://github.com/wso2/docs-ob-toolkit-uk/files/10999324/localhost-8001-conformance-functional-conformance-suite-2023-03-17-13_54_36.pdf)

2023-03-17 08:33 UTC, shadhini requested changes

2023-03-17 08:33 UTC, shadhini commented on en/docs/assets/attachments/endpoint_configuration_for_accounts_API.json
> +
let's add a new line here, please check other places as well

2023-03-17 08:55 UTC, Ashi1993 commented on en/docs/conformance/functional-conformance-suite.md
> +    WSO2 Open Banking 3.0.0 UK Toolkit 1.0.0 supports Functional Conformance Suite  v1.7.1.
Lets comment this for now till we finalize the failing test cases

2023-03-17 13:23 UTC, DinithiDiaz commented on en/docs/assets/attachments/endpoint_configuration_for_accounts_API.json
> +
Fixed via 496494d6e96b06aecae1ee51f1cda3fc6d53253c.

2023-03-17 13:25 UTC, DinithiDiaz commented on en/docs/conformance/functional-conformance-suite.md
> +    WSO2 Open Banking 3.0.0 UK Toolkit 1.0.0 supports Functional Conformance Suite  v1.7.1.
Fixed via 186da86db64dd6e6afa2793c507ead9f036f9e27.

2023-03-17 13:26 UTC, DinithiDiaz commented on en/docs/assets/attachments/endpoint_configuration_for_cof_API.json
> +          "openidConfigurationUri": "https://localhost:9446/oauth2/token/.well-known/openid-configuration",
Fixed via d8f10ecd48983a4e70c6a3cca5018116a7f2e004.

2023-03-17 14:32 UTC, Ashi1993 approved these changes

2023-03-20 10:32 UTC, shadhini approved these changes

2023-03-20 10:35 UTC, merged